module.exports = {
   LOGIN_FORM: "LOGIN_FORM",
   SIGNUP_FORM: "SIGNUP_FORM",
   EDIT_USER_FORM: "EDIT_USER_FORM",
   CREATE_QUESTIONNAIRE_FORM: "CREATE_QUESTIONNAIRE_FORM",
   CREATE_RESPONSE_FORM: "CREATE_RESPONSE_FORM"
};
